Oddevenfixes
scipion-em/scipion-em-imod pull request #226
Opened 2023-11-23 08:17 UTC by Vilax

2023-11-23 08:29 UTC, pconesa requested changes
I got 2 refactorization sugestions and a concern about what will happen if TS does not have even odd?

2023-11-23 08:29 UTC, pconesa commented on imod/protocols/protocol_base.py
> +                    outputOddTsFileName = os.path.join(tmpPrefix, tsId+EXT_MRCS_TS_EVEN_NAME)
Maybe this can be refactored in a single method receiving EXT_MRCS_TS_EVEN_NAME or the ODD one?

2023-11-23 08:29 UTC, pconesa commented on imod/protocols/protocol_tomoReconstruction.py
> +        super().convertInputStep(tsObjId, doSwap=True, oddEven=True)
What if TS does not have even odd?

2023-11-23 08:29 UTC, pconesa commented on imod/protocols/protocol_tomoReconstruction.py
> +            oddFn = os.path.join(tmpPrefix, tsId+EXT_MRCS_TS_ODD_NAME)
Method extraction?

2023-11-23 08:53 UTC, Vilax commented on imod/protocols/protocol_tomoReconstruction.py
> +        super().convertInputStep(tsObjId, doSwap=True, oddEven=True)
Solved!

2023-11-28 14:36 UTC, pconesa commented on imod/protocols/protocol_xCorrPrealignment.py
> +    _possibleOutputs = {"outputSetOfTiltSeries": tomoObj.SetOfTiltSeries}
I think output are named TiltSeries

2023-11-28 14:38 UTC, pconesa commented on imod/protocols/protocol_xCorrPrealignment.py
> +    _possibleOutputs = {"outputSetOfTiltSeries": tomoObj.SetOfTiltSeries}
https://github.com/scipion-em/scipion-em-imod/blob/7207b54fcb61469c8b1ac1315e94277d253dc5f9/imod/protocols/protocol_base.py#L234

2023-11-29 10:29 UTC, fede-pe commented on imod/protocols/protocol_xCorrPrealignment.py
> +    _possibleOutputs = {"outputSetOfTiltSeries": tomoObj.SetOfTiltSeries}
fixed

2023-11-29 10:29 UTC, merged