remove plugin-specific import CTF protocol
scipion-em/scipion-em-imod pull request #243
Opened 2024-01-07 19:44 UTC by azazellochg

Goes together with https://github.com/scipion-em/scipion-em-tomo/pull/439
@fede-pe  please let me know if you are happy with the suggested changes so I can proceed to remove addCTFTomoSeriesToSetFromDefocusFile function and adapt existing estimation protocols code.

2024-01-08 09:44 UTC, fede-pe commented
Hi @azazellochg, I like the idea. I added @pconesa and @JorMaister so they can check the implementation too.

Besides that sonarCloud is not passing due to code duplication but I have no idea how to fix it.

2024-01-08 10:04 UTC, azazellochg commented
Thanks! I'll fix the duplication.

2024-01-13 16:44 UTC, azazellochg commented
All fixed now and ready for review

2024-01-15 10:00 UTC, JorMaister requested changes

2024-01-15 10:00 UTC, JorMaister commented on imod/tests/test_protocols_imod.py
TestImodCTFCorrectionWorkflow is not passing, at least on my machine. 

I got the following error:

[   FAILED ] TestImodCTFCorrectionWorkflow.setUpClass


Traceback (most recent call last):
  File "/home/jjimenez/anaconda3/envs/scipion3/lib/python3.8/unittest/suite.py", line 163, in _handleClassSetUp
    setUpClass()
  File "/home/jjimenez/scipion3/scipion-em-imod/imod/tests/test_protocols_imod.py", line 698, in setUpClass
    cls._runImportSetOfCtfSeries(filesPath=os.path.split(cls.inputCtfFile)[0],
  File "/home/jjimenez/scipion3/scipion-em-imod/imod/tests/test_protocols_imod.py", line 241, in _runImportSetOfCtfSeries
    cls.protImportSetOfCtfSeries = cls.newProtocol(tomo.protocols.ProtImportTsCTF,
AttributeError: module 'tomo.protocols' has no attribute 'ProtImportTsCTF'

2024-01-15 10:00 UTC, JorMaister commented on imod/__init__.py
Just to keep you updated regarding the versioning, we've started to use this semantic versioning recently:

https://semver.org/

Following this, I'd say it's a Minor or even a Major change.

2024-01-15 10:02 UTC, azazellochg commented on imod/tests/test_protocols_imod.py
You need to use this with https://github.com/scipion-em/scipion-em-tomo/pull/439

2024-01-15 10:05 UTC, azazellochg commented on imod/__init__.py
Good point, I bumped it to 3.4

2024-01-15 10:36 UTC, JorMaister approved these changes

2024-01-19 11:10 UTC, pconesa approved these changes

2024-01-19 11:10 UTC, merged